### PR TITLE
`parse_time()` now correctly handles 12 AM/PM

### LINKED ISSUE #579: parse_time fails if 12 pm
```R
parse_time("12:01 PM")
```

Because `DateTimeParser.hour` always adds 12. It should subtract 12 if hour is already 12.

From @cwickham

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #579

### CODE REVIEW

File: src/DateTimeParser.h [hunk 1]
```diff
@@ -311,7 +311,10 @@ class DateTimeParser {
 
 private:
   int hour() {
-    return hour_ + (amPm_ == 1 ? 12 : 0);
+    if (hour_ == 12 && amPm_ == 0) {
```
Comment (hadley) [inline src/DateTimeParser.h]: I feel like this might be simpler if you branched on `hour_ == 12` so you could also simplify the ternary if below.

Comment (jimhester) [inline src/DateTimeParser.h]: Ok I did so with https://github.com/tidyverse/readr/pull/584/commits/6f93d5bd265735a2348a60ed8d62bad02e0b5da4
